// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_REVENUES = "GET_REVENUES";

// Add Revenue
export const ADD_REVENUE = "ADD_REVENUE";
export const ADD_REVENUE_SUCCESS = "ADD_REVENUE_SUCCESS";
export const ADD_REVENUE_FAIL = "ADD_REVENUE_FAIL";

// Edit Revenue
export const UPDATE_REVENUE = "UPDATE_REVENUE";
export const UPDATE_REVENUE_SUCCESS = "UPDATE_REVENUE_SUCCESS";
export const UPDATE_REVENUE_FAIL = "UPDATE_REVENUE_FAIL";

// Delete Revenue
export const DELETE_REVENUE = "DELETE_REVENUE";
export const DELETE_REVENUE_SUCCESS = "DELETE_REVENUE_SUCCESS";
export const DELETE_REVENUE_FAIL = "DELETE_REVENUE_FAIL";
