// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_DAILY_REVENUES = "GET_DAILY_REVENUES";


// Add DailyRevenue

export const ADD_NEW_DAILY_REVENUE = "ADD_NEW_DAILY_REVENUE";
export const ADD_DAILY_REVENUE_SUCCESS = "ADD_DAILY_REVENUE_SUCCESS";
export const ADD_DAILY_REVENUE_FAIL = "ADD_DAILY_REVENUE_FAIL";

// Edit DailyRevenue

export const UPDATE_DAILY_REVENUE = "UPDATE_DAILY_REVENUE";
export const UPDATE_DAILY_REVENUE_SUCCESS = "UPDATE_DAILY_REVENUE_SUCCESS";
export const UPDATE_DAILY_REVENUE_FAIL = "UPDATE_DAILY_REVENUE_FAIL";

// Delete DailyRevenue

export const DELETE_DAILY_REVENUE = "DELETE_DAILY_REVENUE";
export const DELETE_DAILY_REVENUE_SUCCESS = "DELETE_DAILY_REVENUE_SUCCESS";
export const DELETE_DAILY_REVENUE_FAIL = "DELETE_DAILY_REVENUE_FAIL";
