# Generated by Django 4.2.3 on 2024-01-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '__first__'),
        ('staff', '__first__'),
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyRevenue_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('declined', 'Declined')], max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Utilities', 'Utilities'), ('Salon Supplies', 'Salon Supplies'), ('Beauty Products', 'Beauty Products'), ('Business Licensing', 'Business Licensing'), ('Construction/Remodeling', 'Construction/Remodeling'), ('Advertisement Expenses', 'Advertisement Expenses'), ('Professional Services', 'Professional Services'), ('Office Supplies', 'Office Supplies'), ('Travel and Transportation', 'Travel and Transportation'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appointment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentservice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
