# Generated by Django 4.2.3 on 2024-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_dailyrevenue_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrevenue',
            old_name='amount',
            new_name='cash',
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='others',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
