# Generated by Django 4.2.3 on 2024-02-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='optioncategory',
            table='option_category',
        ),
        migrations.AlterModelTable(
            name='optionchoices',
            table='option_choice',
        ),
    ]
