# Generated by Django 4.2.3 on 2024-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_optioncategory_table_alter_optionchoices_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('value', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'option',
                'permissions': [('canViewOptions', 'Can View Options'), ('canAddOptions', 'Can Add Options'), ('canChangeOptions', 'Can Change Options'), ('canDeleteOptions', 'Can Delete Options')],
                'default_permissions': [],
            },
        ),
    ]
