# Generated by Django 4.2.3 on 2024-03-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_option_autoload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='settings_option',
        ),
    ]
