# Generated by Django 4.2.3 on 2024-03-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_option_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='SettingOption',
        ),
        migrations.AlterModelOptions(
            name='settingoption',
            options={'default_permissions': [], 'permissions': [('canViewOptions', 'Can View Options'), ('canAddOptions', 'Can Add Options'), ('canChangeOptions', 'Can Change Options'), ('canDeleteOptions', 'Can Delete Options')], 'verbose_name': 'Setting Option', 'verbose_name_plural': 'Setting Options'},
        ),
    ]
