# Generated by Django 4.2.3 on 2024-03-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_option_settingoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncategory',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
