# Generated by Django 4.2.3 on 2024-02-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='client_appointment',
        ),
        migrations.AlterModelTable(
            name='appointmentservice',
            table='client_appointment_service',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='commission',
            table='finance_comission',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='discount',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='finance_expense',
        ),
        migrations.AlterModelTable(
            name='package',
            table='service_package',
        ),
        migrations.AlterModelTable(
            name='packageitem',
            table='service_package_item',
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='finance_revenue',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table='service_provider',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
