# Generated by Django 4.2.3 on 2024-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='staff_member',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
