# Generated by Django 4.2.3 on 2024-02-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimize_switching', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='match_resources',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspace.resource')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='resources',
            field=models.ManyToManyField(blank=True, to='workspace.resourceitem'),
        ),
    ]
