# Generated by Django 4.2.3 on 2024-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_appointmentproduct_appointmentpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='packages',
            field=models.ManyToManyField(related_name='appointments_package', to='workspace.appointmentpackage'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='products',
            field=models.ManyToManyField(related_name='appointments_product', to='workspace.appointmentproduct'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments_service', to='workspace.appointmentservice'),
        ),
    ]
