# Generated by Django 4.2.3 on 2024-02-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_rename_staff_member_appointmentservice_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_member',
            new_name='staff',
        ),
    ]
