# Generated by Django 4.2.3 on 2024-02-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_appointment_packages_appointment_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
