# Generated by Django 4.2.3 on 2024-02-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.appointment')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.product')),
            ],
            options={
                'db_table': 'appointment_note',
            },
        ),
    ]
