# Generated by Django 4.2.3 on 2024-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
