# Generated by Django 4.2.3 on 2024-02-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_appointmentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentnote',
            name='note',
            field=models.TextField(),
        ),
    ]
