# Generated by Django 4.2.3 on 2024-02-08 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_service_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client_notification_settings',
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='customer_type',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='clientadditionalinfo',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='clientadditionalinfo',
            name='no_shows',
        ),
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientadditionalinfo',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientadditionalinfo',
            name='mobile_alt',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientadditionalinfo',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientadditionalinfo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.client'),
        ),
    ]
