# Generated by Django 4.2.3 on 2024-02-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_appointmentnote_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnote',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='workspace.appointment'),
        ),
    ]
