# Generated by Django 4.2.3 on 2024-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_alter_appointmentnote_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_custom_amount', models.BooleanField(default=False)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_redeemable_online', models.BooleanField(default=False)),
                ('is_voidable', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('template1', 'voucher template 1'), ('template2', 'voucher template 2'), ('template3', 'voucher template 3'), ('template4', 'voucher template 4')], max_length=50)),
                ('expiry_months', models.PositiveIntegerField(default=1)),
                ('terms', models.TextField()),
                ('custom_voucher_code_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'voucher',
            },
        ),
    ]
