# Generated by Django 4.2.3 on 2024-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_clientnotification_rename_customer_type_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
