# Generated by Django 4.2.3 on 2024-02-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='template',
            field=models.CharField(choices=[('mothersday', 'voucher template 1'), ('birthday', 'voucher template 2'), ('valentinesday', 'voucher template 3'), ('anniversary', 'voucher template 4')], max_length=50),
        ),
    ]
