# Generated by Django 4.2.3 on 2024-02-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_alter_voucher_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='template',
            new_name='category',
        ),
    ]
