# Generated by Django 4.2.3 on 2024-02-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_appointment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='category_color',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='subject',
        ),
    ]
