# Generated by Django 4.2.3 on 2024-02-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_remove_appointment_category_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
    ]
