# Generated by Django 4.2.3 on 2024-03-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_rename_template_voucher_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='start_time',
            new_name='start',
        ),
    ]
