# Generated by Django 4.2.3 on 2024-03-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_rename_end_time_appointment_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'pencilled-in'), (2, 'not-started'), (3, 'arrived'), (4, 'started'), (5, 'completed'), (6, 'did-not-show'), (7, 'cancelled')], default=1, null=True),
        ),
    ]
