# Generated by Django 4.2.3 on 2024-02-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_remove_appointment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
