# Generated by Django 4.2.3 on 2024-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_rename_transaction_date_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
