# Generated by Django 4.2.3 on 2024-03-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_remove_invoice_description_alter_invoice_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvoiceService',
        ),
        migrations.AddField(
            model_name='invoicetransactions',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workspace.invoice'),
        ),
        migrations.AddField(
            model_name='invoicetransactions',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workspace.transaction'),
        ),
        migrations.AddField(
            model_name='invoiceappointment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workspace.invoice'),
        ),
    ]
