# Generated by Django 4.2.3 on 2024-03-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_invoiceappointment_invoicetransactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='payment_type',
        ),
    ]
