# Generated by Django 4.2.3 on 2024-02-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_appointment_end_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.RemoveField(
            model_name='appointmentservice',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(default=149, on_delete=django.db.models.deletion.CASCADE, to='workspace.appointment'),
            preserve_default=False,
        ),
    ]
