# Generated by Django 4.2.3 on 2024-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_rename_transaction_type_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('appoiuntment', 'Appoiuntment'), ('online Sale', 'OnlineSale')], default='appoiuntment', max_length=100),
        ),
    ]
