# Generated by Django 4.2.3 on 2024-02-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_remove_appointmentservice_match_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentservice',
            name='service',
        ),
    ]
