# Generated by Django 4.2.3 on 2024-03-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_invoice_invoice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepackage',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='invoicepackage',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicepackage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
