# Generated by Django 4.2.3 on 2024-03-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_alter_invoice_amount_alter_invoiceappointment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceappointment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.invoice'),
        ),
    ]
