# Generated by Django 4.2.3 on 2024-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_appointmentservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentservice',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_service',
            field=models.ManyToManyField(related_name='appointments', to='workspace.appointmentservice'),
        ),
    ]
