# Generated by Django 4.2.3 on 2024-03-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0020_alter_invoiceappointment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicepackage',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
            preserve_default=False,
        ),
    ]
