# Generated by Django 4.2.3 on 2024-02-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0020_remove_appointmentservice_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_service',
            new_name='services',
        ),
    ]
