# Generated by Django 4.2.3 on 2024-03-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0021_invoice_staff_invoicepackage_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
        ),
        migrations.AlterField(
            model_name='invoicepackage',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.staff'),
        ),
    ]
