# Generated by Django 4.2.3 on 2024-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0022_invoice_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
