# Generated by Django 4.2.3 on 2024-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0025_remove_appointment_recurrence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'pencilled-in'), (2, 'confirmed'), (3, 'arrived'), (4, 'finished'), (5, 'no-show-up'), (9, 'cancelled')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
