// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_SETTING_OPTIONS = "GET_SETTING_OPTIONS";

// Edit SettingOption
export const UPDATE_SETTING_OPTION = "UPDATE_SETTING_OPTION";
export const UPDATE_SETTING_OPTION_SUCCESS = "UPDATE_SETTING_OPTION_SUCCESS";
export const UPDATE_SETTING_OPTION_FAIL = "UPDATE_SETTING_OPTION_FAIL";
