// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

/* Get Schedule */
export const GET_SCHEDULE = "GET_SCHEDULE";

// Appointments
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";

// Add Appointment
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_FAIL = "ADD_APPOINTMENT_FAIL";

// Edit Appointment
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_FAIL = "UPDATE_APPOINTMENT_FAIL";

// Delete Appointment
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIL";



// AppointmentServices
export const GET_APPOINTMENT_SERVICES = "GET_APPOINTMENT_SERVICES";

// Add AppointmentService
export const ADD_APPOINTMENT_SERVICE = "ADD_APPOINTMENT_SERVICE";
export const ADD_APPOINTMENT_SERVICE_SUCCESS = "ADD_APPOINTMENT_SERVICE_SUCCESS";
export const ADD_APPOINTMENT_SERVICE_FAIL = "ADD_APPOINTMENT_SERVICE_FAIL";

// Edit AppointmentService
export const UPDATE_APPOINTMENT_SERVICE = "UPDATE_APPOINTMENT_SERVICE";
export const UPDATE_APPOINTMENT_SERVICE_SUCCESS = "UPDATE_APPOINTMENT_SERVICE_SUCCESS";
export const UPDATE_APPOINTMENT_SERVICE_FAIL = "UPDATE_APPOINTMENT_SERVICE_FAIL";

// Delete AppointmentService
export const DELETE_APPOINTMENT_SERVICE = "DELETE_APPOINTMENT_SERVICE";
export const DELETE_APPOINTMENT_SERVICE_SUCCESS = "DELETE_APPOINTMENT_SERVICE_SUCCESS";
export const DELETE_APPOINTMENT_SERVICE_FAIL = "DELETE_APPOINTMENT_SERVICE_FAIL";
