// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_OPTION_CHOICES = "GET_OPTION_CHOICES";

// Add OptionChoice
export const ADD_OPTION_CHOICE = "ADD_OPTION_CHOICE";
export const ADD_OPTION_CHOICE_SUCCESS = "ADD_OPTION_CHOICE_SUCCESS";
export const ADD_OPTION_CHOICE_FAIL = "ADD_OPTION_CHOICE_FAIL";

// Edit OptionChoice
export const UPDATE_OPTION_CHOICE = "UPDATE_OPTION_CHOICE";
export const UPDATE_OPTION_CHOICE_SUCCESS = "UPDATE_OPTION_CHOICE_SUCCESS";
export const UPDATE_OPTION_CHOICE_FAIL = "UPDATE_OPTION_CHOICE_FAIL";

// Delete OptionChoice
export const DELETE_OPTION_CHOICE = "DELETE_OPTION_CHOICE";
export const DELETE_OPTION_CHOICE_SUCCESS = "DELETE_OPTION_CHOICE_SUCCESS";
export const DELETE_OPTION_CHOICE_FAIL = "DELETE_OPTION_CHOICE_FAIL";
