// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_RESOURCES = "GET_RESOURCES";

// Add Resource
export const ADD_RESOURCE = "ADD_RESOURCE";
export const ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS";
export const ADD_RESOURCE_FAIL = "ADD_RESOURCE_FAIL";

// Edit Resource
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS";
export const UPDATE_RESOURCE_FAIL = "UPDATE_RESOURCE_FAIL";

// Delete Resource
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAIL = "DELETE_RESOURCE_FAIL";
